apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs
  namespace: superdevs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs-service-account-cluster-admin
  namespace: superdevs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: superdevs
  namespace: superdevs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs-team
  namespace: superdevs
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - helmcharts
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - pac.weave.works
  resources:
  - policies
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - flagger.app
  resources:
  - canaries
  - metrictemplates
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs-team
  namespace: superdevs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: superdevs-team
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: team-pmm@weave.works
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: test
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs-service-account-cluster-admin
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: superdevs
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs-team
  namespace: test
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - helmcharts
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - pac.weave.works
  resources:
  - policies
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - flagger.app
  resources:
  - canaries
  - metrictemplates
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: superdevs-team
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: superdevs-team
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: team-pmm@weave.works
---
apiVersion: pac.weave.works/v2beta1
kind: Policy
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: weave.policies.tenancy.superdevs-allowed-application-deploy
spec:
  category: weave.categories.tenancy
  code: |
    package weave.tenancy.allowed_application_deploy

    controller_input := input.review.object
    violation[result] {
        namespaces := input.parameters.namespaces
        targetNamespace := controller_input.spec.targetNamespace
        not contains_array(targetNamespace, namespaces)
        result = {
        "issue detected": true,
        "msg": sprintf("using target namespace %v is not allowed", [targetNamespace]),
        }
    }
    violation[result] {
        serviceAccountName := controller_input.spec.serviceAccountName
        serviceAccountName != input.parameters.service_account_name
        result = {
        "issue detected": true,
        "msg": sprintf("using service account name %v is not allowed", [serviceAccountName]),
        }
    }
    contains_array(item, items) {
        items[_] = item
    }
  description: Determines which helm release and kustomization can be used in a tenant
  how_to_solve: ""
  id: weave.policies.tenancy.superdevs-allowed-application-deploy
  name: superdevs allowed application deploy
  parameters:
  - name: namespaces
    required: false
    type: array
    value:
    - superdevs
    - test
  - name: service_account_name
    required: false
    type: string
    value: superdevs
  severity: high
  standards: []
  tags:
  - tenancy
  targets:
    kinds:
    - HelmRelease
    - Kustomization
    labels: []
    namespaces:
    - superdevs
    - test
---
apiVersion: pac.weave.works/v2beta1
kind: Policy
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: weave.policies.tenancy.superdevs-allowed-repositories
spec:
  category: weave.categories.tenancy
  code: |
    package weave.tenancy.allowed_repositories

    controller_input := input.review.object
    namespace := controller_input.metadata.namespace
    violation[result] {
        controller_input.kind == "GitRepository"
        urls := input.parameters.git_urls
        url := controller_input.spec.url
        not contains_array(url, urls)
        result = {
        "issue detected": true,
        "msg": sprintf("Git repository url %v is not allowed for namespace %v", [url, namespace]),
        }
    }
    violation[result] {
        controller_input.kind == "Bucket"
        urls := input.parameters.bucket_endpoints
        url := controller_input.spec.endpoint
        not contains_array(url, urls)
        result = {
        "issue detected": true,
        "msg": sprintf("Bucket endpoint %v is not allowed for namespace %v", [url, namespace]),
        }
    }
    violation[result] {
        controller_input.kind == "HelmRepository"
        urls := input.parameters.helm_urls
        url := controller_input.spec.url
        not contains_array(url, urls)
        result = {
        "issue detected": true,
        "msg": sprintf("Helm repository url %v is not allowed for namespace %v", [url, namespace]),
        }
    }
    violation[result] {
        controller_input.kind == "OCIRepository"
        urls := input.parameters.oci_urls
        url := controller_input.spec.url
        not contains_array(url, urls)
        result = {
        "issue detected": true,
        "msg": sprintf("OCI repository url %v is not allowed for namespace %v", [url, namespace]),
        }
    }
    contains_array(item, items) {
        items[_] = item
    }
  description: Controls the allowed repositories to be used as sources
  how_to_solve: ""
  id: weave.policies.tenancy.superdevs-allowed-repositories
  name: superdevs allowed repositories
  parameters:
  - name: git_urls
    required: false
    type: array
    value:
    - https://github.com/weavegitops/demo2-repo
    - https://github.com/sympatheticmoose/podinfo
    - https://github.com/sympatheticmoose/superdevs-apps
  - name: bucket_endpoints
    required: false
    type: array
    value: null
  - name: helm_urls
    required: false
    type: array
    value: null
  - name: oci_urls
    required: false
    type: array
    value: null
  severity: high
  standards: []
  tags:
  - tenancy
  targets:
    kinds:
    - GitRepository
    - Bucket
    - HelmRepository
    - OCIRepository
    labels: []
    namespaces:
    - superdevs
    - test
---
apiVersion: pac.weave.works/v2beta1
kind: Policy
metadata:
  creationTimestamp: null
  labels:
    toolkit.fluxcd.io/tenant: superdevs
  name: weave.policies.tenancy.superdevs-allowed-clusters
spec:
  category: weave.categories.tenancy
  code: |
    package weave.tenancy.allowed_clusters

    controller_input := input.review.object
    namespace := controller_input.metadata.namespace
    secrets := input.parameters.cluster_secrets
    violation[result] {
        controller_input.kind == "GitopsCluster"
        secret := controller_input.spec.secretRef.name
        not contains_array(secret, secrets)
        result = {
        "issue detected": true,
        "msg": sprintf("cluster secretRef %v is not allowed for namespace %v", [secret, namespace]),
        }
    }
    violation[result] {
        controller_input.kind == "Kustomization"
        secret := controller_input.spec.kubeConfig.secretRef.name
        not contains_array(secret, secrets)
        result = {
        "issue detected": true,
        "msg": sprintf("kustomization kubeconfig secretRef %v is not allowed for namespace %v", [secret, namespace]),
        }
    }
    contains_array(item, items) {
        items[_] = item
    }
  description: Controls the allowed clusters to be added
  how_to_solve: ""
  id: weave.policies.tenancy.superdevs-allowed-clusters
  name: superdevs allowed clusters
  parameters:
  - name: cluster_secrets
    required: false
    type: array
    value:
    - demo-28-kubeconfig
  severity: high
  standards: []
  tags:
  - tenancy
  targets:
    kinds:
    - GitopsCluster
    - Kustomization
    labels: []
    namespaces:
    - superdevs
    - test
---
