apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-weave-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./apps/weave-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-templates
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This creates a set of examples templates for self service
spec:
  interval: 1h0m0s
  path: ./apps/templates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gcloud-terraform
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is a set of sample terraform objects using tf-controller
spec:
  interval: 1h0m0s
  path: ./apps/terraform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true